use std::cell::RefCell;
use std::collections::BTreeMap;
use std::env;
use std::path::PathBuf;
use std::process::Command;
use std::rc::Rc;
use std::time::Duration;

use mlua::{Lua, Table, Value};
use regex::Regex;
use reqwest::blocking::Client;
use reqwest::header::{HeaderMap, HeaderValue};
use serde_json::Value as JsonValue;
use tracing::{debug, info, warn, error};

use crate::error::AppError;

// Generated by build.rs from src/statusline-providers/*.lua
include!(concat!(env!("OUT_DIR"), "/statusline_providers.rs"));

macro_rules! lua_err {
    ($provider:expr, $e:expr) => {
        AppError::StatuslineLua {
            provider: $provider.to_string(),
            message: $e.to_string(),
        }
    };
}

pub fn run_parts(
    stdin_data: &JsonValue,
    no_cache: bool,
) -> Result<String, AppError> {
    let lua = Lua::new();

    let accessed: Rc<RefCell<Vec<String>>> = Rc::new(RefCell::new(Vec::new()));
    inject_bridges(&lua, accessed.clone()).map_err(|e| lua_err!("bridge", e))?;
    load_util(&lua)?;

    let scripts = discover_scripts()?;
    info!("discovered {} statusline part scripts", scripts.len());

    let mut output = String::new();
    let mut display_index: u32 = 0;

    for (idx, filename, lua_code) in &scripts {
        debug!("processing script: idx={idx} file={filename}");

        let module: Table = match lua.load(lua_code).set_name(filename).eval() {
            Ok(t) => t,
            Err(e) => {
                warn!("failed to load {filename}: {e}");
                continue;
            }
        };

        let ctx = build_context_table(&lua, stdin_data, accessed.clone())?;

        let matcher_fn: mlua::Function = match module.get("matcher") {
            Ok(f) => f,
            Err(_) => {
                warn!("{filename}: no matcher function, skipping");
                continue;
            }
        };

        let matched: bool = match matcher_fn.call(ctx.clone()) {
            Ok(Value::Boolean(b)) => b,
            Ok(_) => false,
            Err(e) => {
                warn!("{filename}: matcher error: {e}");
                continue;
            }
        };

        if !matched {
            debug!("{filename}: matcher returned false");
            continue;
        }

        info!("{filename}: matched, display_index={display_index}");

        // Check cache hints
        let part_output = if let Ok(hints_fn) = module.get::<mlua::Function>("cache_hints") {
            match hints_fn.call::<Table>(()) {
                Ok(hints) => {
                    let key = hints.get::<String>("key").unwrap_or_default();
                    let env_list = hints.get::<Table>("env").unwrap_or_else(|_| lua.create_table().unwrap());
                    let mut env_depends = Vec::new();
                    for val in env_list.sequence_values::<String>() {
                        if let Ok(s) = val {
                            env_depends.push(s);
                        }
                    }

                    match super::cache::cache_check(&key, &env_depends, no_cache) {
                        super::cache::CacheResult::Hit(cached) => {
                            info!("{filename}: cache hit, key={key}");
                            cached
                        }
                        super::cache::CacheResult::Miss => {
                            let result = run_part(&lua, &module, &ctx, display_index, filename)?;
                            if !result.is_empty() {
                                super::cache::cache_write(&key, &result, &env_depends);
                            }
                            result
                        }
                    }
                }
                Err(e) => {
                    warn!("{filename}: cache_hints error: {e}");
                    run_part(&lua, &module, &ctx, display_index, filename)?
                }
            }
        } else {
            // No cache_hints — always run
            if let Ok(cmds_fn) = module.get::<mlua::Function>("extra_context_commands") {
                if let Ok(cmds) = cmds_fn.call::<Table>(()) {
                    execute_and_inject_commands(&lua, &ctx, &cmds)?;
                }
            }
            run_part_raw(&module, &ctx, display_index, filename)?
        };

        output.push_str(&part_output);
        display_index += 1;
        info!("{filename}: part output = {part_output:?}");
    }

    debug!("env vars accessed by scripts: {:?}", accessed.borrow());
    info!("final statusline: {output:?}");
    Ok(output)
}

fn run_part(
    lua: &Lua,
    module: &Table,
    ctx: &Table,
    display_index: u32,
    filename: &str,
) -> Result<String, AppError> {
    if let Ok(cmds_fn) = module.get::<mlua::Function>("extra_context_commands") {
        if let Ok(cmds) = cmds_fn.call::<Table>(()) {
            execute_and_inject_commands(lua, ctx, &cmds)?;
        }
    }
    run_part_raw(module, ctx, display_index, filename)
}

fn run_part_raw(
    module: &Table,
    ctx: &Table,
    display_index: u32,
    filename: &str,
) -> Result<String, AppError> {
    ctx.set("display_index", display_index)
        .map_err(|e| lua_err!(filename, e))?;

    let part_fn: mlua::Function = module
        .get("statusline_part")
        .map_err(|e| lua_err!(filename, e))?;

    let part_output: String = match part_fn.call::<String>((display_index, ctx.clone())) {
        Ok(s) => s,
        Err(e) => {
            warn!("{filename}: statusline_part error: {e}");
            String::new()
        }
    };

    Ok(part_output)
}

fn inject_bridges(lua: &Lua, _accessed: Rc<RefCell<Vec<String>>>) -> Result<(), mlua::Error> {
    let globals = lua.globals();

    // now
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs_f64();
    globals.set("now", now)?;

    // http_get
    let http_fn = lua.create_function(|lua, (url, headers): (String, Option<Table>)| {
        let client = Client::builder()
            .timeout(Duration::from_secs(2))
            .build()
            .map_err(|e| mlua::Error::external(format!("http client: {e}")))?;

        let mut req = client.get(&url);
        if let Some(hdrs) = headers {
            let mut header_map = HeaderMap::new();
            for pair in hdrs.pairs::<String, String>() {
                let (k, v) = pair?;
                let name = reqwest::header::HeaderName::from_bytes(k.as_bytes())
                    .map_err(|e| mlua::Error::external(format!("header: {e}")))?;
                let val = HeaderValue::from_str(&v)
                    .map_err(|e| mlua::Error::external(format!("header: {e}")))?;
                header_map.insert(name, val);
            }
            req = req.headers(header_map);
        }

        match req.send() {
            Ok(resp) => {
                let status = resp.status().as_u16();
                let body = resp.text().unwrap_or_default();
                let tbl = lua.create_table()?;
                tbl.set("status", status)?;
                tbl.set("body", body)?;
                Ok(Value::Table(tbl))
            }
            Err(e) => {
                let tbl = lua.create_table()?;
                tbl.set("status", 0u16)?;
                tbl.set("body", format!("error: {e}"))?;
                Ok(Value::Table(tbl))
            }
        }
    })?;
    globals.set("http_get", http_fn)?;

    // json_decode
    let json_fn = lua.create_function(|lua, s: String| {
        let val: JsonValue = serde_json::from_str(&s)
            .map_err(|e| mlua::Error::external(format!("json: {e}")))?;
        json_to_lua(lua, &val)
    })?;
    globals.set("json_decode", json_fn)?;

    // regex_match
    let regex_match_fn = lua.create_function(|_, (s, pattern): (String, String)| {
        let re = Regex::new(&pattern)
            .map_err(|e| mlua::Error::external(format!("regex: {e}")))?;
        Ok(re.is_match(&s))
    })?;
    globals.set("regex_match", regex_match_fn)?;

    // regex_find
    let regex_find_fn = lua.create_function(|lua, (s, pattern): (String, String)| {
        let re = Regex::new(&pattern)
            .map_err(|e| mlua::Error::external(format!("regex: {e}")))?;
        match re.captures(&s) {
            Some(caps) => {
                let tbl = lua.create_table()?;
                for (i, m) in caps.iter().enumerate() {
                    if let Some(m) = m {
                        tbl.set(i + 1, m.as_str())?;
                    }
                }
                Ok(Value::Table(tbl))
            }
            None => Ok(Value::Nil),
        }
    })?;
    globals.set("regex_find", regex_find_fn)?;

    Ok(())
}

fn load_util(lua: &Lua) -> Result<(), AppError> {
    let util_code = EMBEDDED_SCRIPTS
        .iter()
        .find(|(name, _)| *name == "_util.lua")
        .map(|(_, code)| *code)
        .unwrap_or("");

    if util_code.is_empty() {
        return Ok(());
    }

    let util_table = lua
        .load(util_code)
        .set_name("_util.lua")
        .eval::<Table>()
        .map_err(|e| {
            error!("_util.lua load failed: {e}");
            lua_err!("_util", e)
        })?;

    debug!("_util.lua evaluated successfully, registering in package.loaded");

    let globals = lua.globals();
    let package: Table = globals.get("package").map_err(|e| lua_err!("package", e))?;
    let loaded: Table = package.get("loaded").map_err(|e| lua_err!("loaded", e))?;
    loaded
        .set("_util", util_table)
        .map_err(|e| lua_err!("loaded._util", e))?;

    debug!("_util.lua registered in package.loaded");

    Ok(())
}

type ScriptEntry = (u32, String, String);

fn discover_scripts() -> Result<Vec<ScriptEntry>, AppError> {
    let mut scripts: BTreeMap<String, ScriptEntry> = BTreeMap::new();

    // Embedded
    for (filename, code) in EMBEDDED_SCRIPTS {
        if filename.starts_with('_') {
            continue;
        }
        if let Some((idx, _id)) = parse_filename(filename) {
            scripts.insert(filename.to_string(), (idx, filename.to_string(), code.to_string()));
        }
    }

    // XDG overlay
    if let Some(xdg_dir) = xdg_providers_dir() {
        if xdg_dir.exists() {
            if let Ok(entries) = std::fs::read_dir(&xdg_dir) {
                for entry in entries.flatten() {
                    let name = entry.file_name().to_string_lossy().to_string();
                    if !name.ends_with(".lua") || name.starts_with('_') {
                        continue;
                    }
                    if let Some((idx, _id)) = parse_filename(&name) {
                        if let Ok(code) = std::fs::read_to_string(entry.path()) {
                            scripts.insert(name.clone(), (idx, name, code));
                        }
                    }
                }
            }
        }
    }

    let mut result: Vec<ScriptEntry> = scripts.into_values().collect();
    result.sort_by_key(|(idx, _, _)| *idx);
    Ok(result)
}

fn parse_filename(name: &str) -> Option<(u32, String)> {
    let without_ext = name.strip_suffix(".lua")?;
    let dash_pos = without_ext.find('-')?;
    let idx_str = &without_ext[..dash_pos];
    let idx: u32 = idx_str.parse().ok()?;
    let id = without_ext[dash_pos + 1..].to_string();
    Some((idx, id))
}

fn xdg_providers_dir() -> Option<PathBuf> {
    if let Ok(xdg) = env::var("XDG_CONFIG_HOME") {
        return Some(PathBuf::from(xdg).join("agent-run").join("statusline-providers"));
    }
    let home = env::var("HOME").ok()?;
    Some(
        PathBuf::from(home)
            .join(".config")
            .join("agent-run")
            .join("statusline-providers"),
    )
}

fn build_context_table(
    lua: &Lua,
    stdin_data: &JsonValue,
    accessed: Rc<RefCell<Vec<String>>>,
) -> Result<Table, AppError> {
    let ctx = lua.create_table().map_err(|e| lua_err!("context", e))?;

    // stdin
    let stdin_table = json_to_lua(lua, stdin_data).map_err(|e| lua_err!("stdin", e))?;
    ctx.set("stdin", stdin_table)
        .map_err(|e| lua_err!("stdin", e))?;

    // env — proxy object with lazy access
    let env_table = lua.create_table().map_err(|e| lua_err!("env", e))?;
    let env_meta = lua.create_table().map_err(|e| lua_err!("env_meta", e))?;
    env_meta
        .set(
            "__index",
            lua.create_function(move |lua, (tbl, key): (Table, String)| {
                accessed.borrow_mut().push(key.clone());
                match env::var(&key) {
                    Ok(val) => {
                        let s = lua.create_string(&val)?;
                        tbl.raw_set(key.as_str(), s.clone())?;
                        Ok(Value::String(s))
                    }
                    Err(_) => Ok(Value::Nil),
                }
            })
            .map_err(|e| lua_err!("env_meta.__index", e))?,
        )
        .map_err(|e| lua_err!("env_meta", e))?;
    env_table
        .set_metatable(Some(env_meta));
    ctx.set("env", env_table)
        .map_err(|e| lua_err!("env", e))?;

    // cwd
    let cwd = stdin_data
        .get("cwd")
        .or_else(|| stdin_data.get("workspace").and_then(|w| w.get("current_dir")))
        .and_then(JsonValue::as_str)
        .map(String::from)
        .or_else(|| env::current_dir().ok().map(|p| p.to_string_lossy().into_owned()))
        .unwrap_or_default();

    ctx.set("cwd", cwd.as_str())
        .map_err(|e| lua_err!("cwd", e))?;
    ctx.set("cwd_short", super::context::short_path(&cwd))
        .map_err(|e| lua_err!("cwd_short", e))?;

    // git
    let git = super::context::git_info(&cwd);
    let git_table = lua.create_table().map_err(|e| lua_err!("git", e))?;
    if let Some(branch) = &git.branch {
        git_table
            .set("branch", branch.as_str())
            .map_err(|e| lua_err!("git", e))?;
    }
    git_table
        .set("dirty", git.dirty)
        .map_err(|e| lua_err!("git", e))?;
    ctx.set("git", git_table)
        .map_err(|e| lua_err!("git", e))?;

    Ok(ctx)
}

fn execute_and_inject_commands(lua: &Lua, ctx: &Table, cmds: &Table) -> Result<(), AppError> {
    for pair in cmds.pairs::<String, Table>() {
        let (key, args_table) = pair.map_err(|e| AppError::StatuslineLua {
            provider: "extra_context_commands".to_string(),
            message: format!("parse: {e}"),
        })?;

        let mut args: Vec<String> = Vec::new();
        for val in args_table.sequence_values::<String>() {
            if let Ok(s) = val {
                args.push(s);
            }
        }

        let result_table = lua.create_table().map_err(|e| lua_err!(&key, e))?;
        if !args.is_empty() {
            match Command::new(&args[0]).args(&args[1..]).output() {
                Ok(out) => {
                    let stdout = String::from_utf8_lossy(&out.stdout).trim().to_string();
                    let stderr = String::from_utf8_lossy(&out.stderr).trim().to_string();
                    result_table
                        .set("stdout", stdout)
                        .map_err(|e| lua_err!(&key, e))?;
                    result_table
                        .set("stderr", stderr)
                        .map_err(|e| lua_err!(&key, e))?;
                }
                Err(e) => {
                    result_table
                        .set("stdout", "")
                        .map_err(|e| lua_err!(&key, e))?;
                    result_table
                        .set("stderr", format!("error: {e}"))
                        .map_err(|e| lua_err!(&key, e))?;
                }
            }
        } else {
            result_table
                .set("stdout", "")
                .map_err(|e| lua_err!(&key, e))?;
            result_table
                .set("stderr", "")
                .map_err(|e| lua_err!(&key, e))?;
        }

        ctx.set(key, result_table)
            .map_err(|e| lua_err!("cmd_result", e))?;
    }

    Ok(())
}

fn json_to_lua(lua: &Lua, val: &JsonValue) -> mlua::Result<Value> {
    match val {
        JsonValue::Null => Ok(Value::Nil),
        JsonValue::Bool(b) => Ok(Value::Boolean(*b)),
        JsonValue::Number(n) => Ok(Value::Number(n.as_f64().unwrap_or(0.0))),
        JsonValue::String(s) => lua.create_string(s).map(Value::String),
        JsonValue::Array(arr) => {
            let tbl = lua.create_table()?;
            for (i, v) in arr.iter().enumerate() {
                tbl.set(i + 1, json_to_lua(lua, v)?)?;
            }
            Ok(Value::Table(tbl))
        }
        JsonValue::Object(map) => {
            let tbl = lua.create_table()?;
            for (k, v) in map {
                tbl.set(k.as_str(), json_to_lua(lua, v)?)?;
            }
            Ok(Value::Table(tbl))
        }
    }
}
