use std::fs;
use std::sync::Arc;

use mlua::{Lua, MetaMethod, Table, UserData, UserDataMethods, Value};
use serde_json::Value as JsonValue;
use tracing::{debug, trace};

use crate::config::model_script_dir;
use crate::error::AppError;
use crate::model::{ModelSpec, ModelSpecPatch};

// Generated by build.rs from src/model.d/*.lua
include!(concat!(env!("OUT_DIR"), "/model_scripts.rs"));

pub fn enrich_models(
    provider_name: &str,
    models: &[ModelSpec],
    raw_response: &JsonValue,
) -> Result<Vec<ModelSpecPatch>, AppError> {
    let Some(script) = resolve_script(provider_name)? else {
        trace!(
            provider = provider_name,
            "no model lua script found for provider"
        );
        return Ok(Vec::new());
    };

    let lua = Lua::new();
    let globals = lua.globals();
    let models_table = build_models_table(&lua, models)
        .map_err(|err| model_lua_err(provider_name, &script.name, err))?;
    globals
        .set("models", models_table)
        .map_err(|err| model_lua_err(provider_name, &script.name, err))?;
    globals
        .set(
            "model_response",
            lua.create_userdata(JsonView::new(raw_response.clone()))
                .map_err(|err| model_lua_err(provider_name, &script.name, err))?,
        )
        .map_err(|err| model_lua_err(provider_name, &script.name, err))?;

    let result: Value = lua
        .load(&script.code)
        .set_name(&script.name)
        .eval()
        .map_err(|err| model_lua_err(provider_name, &script.name, err))?;
    let patches = parse_patch_result(provider_name, &script.name, result)?;
    debug!(
        provider = provider_name,
        script = script.name,
        patch_count = patches.len(),
        "applied model lua enrichment"
    );
    Ok(patches)
}

struct ModelLuaScript {
    name: String,
    code: String,
}

fn resolve_script(provider_name: &str) -> Result<Option<ModelLuaScript>, AppError> {
    let file_name = format!("{provider_name}.lua");
    let override_path = model_script_dir()?.join(&file_name);
    if override_path.exists() {
        let code = fs::read_to_string(&override_path).map_err(|source| AppError::ReadConfig {
            path: override_path.clone(),
            source,
        })?;
        return Ok(Some(ModelLuaScript {
            name: override_path.display().to_string(),
            code,
        }));
    }

    let Some((_, code)) = EMBEDDED_MODEL_SCRIPTS
        .iter()
        .find(|(name, _)| *name == file_name)
    else {
        return Ok(None);
    };

    Ok(Some(ModelLuaScript {
        name: format!("embedded:{file_name}"),
        code: (*code).to_string(),
    }))
}

fn build_models_table(lua: &Lua, models: &[ModelSpec]) -> Result<Table, mlua::Error> {
    let result = lua.create_table()?;
    for (index, model) in models.iter().enumerate() {
        let item = lua.create_table()?;
        item.set("id", model.id.clone())?;
        if let Some(name) = &model.name {
            item.set("name", name.clone())?;
        }
        if let Some(context_window) = model.context_window {
            item.set("context_window", context_window)?;
        }
        if let Some(max_output_tokens) = model.max_output_tokens {
            item.set("max_output_tokens", max_output_tokens)?;
        }
        if let Some(reasoning) = model.reasoning {
            item.set("reasoning", reasoning)?;
        }
        if let Some(vision) = model.vision {
            item.set("vision", vision)?;
        }
        if let Some(supports_attachments) = model.supports_attachments {
            item.set("supports_attachments", supports_attachments)?;
        }
        if let Some(input_cost_per_million) = model.input_cost_per_million {
            item.set("input_cost_per_million", input_cost_per_million)?;
        }
        if let Some(output_cost_per_million) = model.output_cost_per_million {
            item.set("output_cost_per_million", output_cost_per_million)?;
        }
        if let Some(cached_input_cost_per_million) = model.cached_input_cost_per_million {
            item.set(
                "cached_input_cost_per_million",
                cached_input_cost_per_million,
            )?;
        }
        if let Some(cached_output_cost_per_million) = model.cached_output_cost_per_million {
            item.set(
                "cached_output_cost_per_million",
                cached_output_cost_per_million,
            )?;
        }
        result.set(index + 1, item)?;
    }
    Ok(result)
}

fn parse_patch_result(
    provider_name: &str,
    script_name: &str,
    result: Value,
) -> Result<Vec<ModelSpecPatch>, AppError> {
    match result {
        Value::Nil => Ok(Vec::new()),
        Value::Table(table) => parse_patch_array(provider_name, script_name, &table),
        other => Err(AppError::ModelLua {
            provider: provider_name.to_string(),
            script: script_name.to_string(),
            message: format!(
                "script must return an array table or nil, got {}",
                lua_value_kind(&other)
            ),
        }),
    }
}

fn parse_patch_array(
    provider_name: &str,
    script_name: &str,
    table: &Table,
) -> Result<Vec<ModelSpecPatch>, AppError> {
    let mut patches = Vec::new();
    for (index, pair) in table.clone().sequence_values::<Table>().enumerate() {
        let item = pair.map_err(|err| model_lua_err(provider_name, script_name, err))?;
        let id = item
            .get::<Option<String>>("id")
            .map_err(|err| model_lua_err(provider_name, script_name, err))?
            .ok_or_else(|| AppError::ModelLua {
                provider: provider_name.to_string(),
                script: script_name.to_string(),
                message: format!("patch item {} is missing required field `id`", index + 1),
            })?;
        patches.push(ModelSpecPatch {
            id,
            name: item
                .get("name")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            context_window: item
                .get("context_window")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            max_output_tokens: item
                .get("max_output_tokens")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            reasoning: item
                .get("reasoning")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            vision: item
                .get("vision")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            supports_attachments: item
                .get("supports_attachments")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            input_cost_per_million: item
                .get("input_cost_per_million")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            output_cost_per_million: item
                .get("output_cost_per_million")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            cached_input_cost_per_million: item
                .get("cached_input_cost_per_million")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
            cached_output_cost_per_million: item
                .get("cached_output_cost_per_million")
                .map_err(|err| model_lua_err(provider_name, script_name, err))?,
        });
    }
    Ok(patches)
}

fn model_lua_err(provider_name: &str, script_name: &str, err: mlua::Error) -> AppError {
    AppError::ModelLua {
        provider: provider_name.to_string(),
        script: script_name.to_string(),
        message: err.to_string(),
    }
}

fn lua_value_kind(value: &Value) -> &'static str {
    match value {
        Value::Nil => "nil",
        Value::Boolean(_) => "boolean",
        Value::LightUserData(_) => "lightuserdata",
        Value::Integer(_) => "integer",
        Value::Number(_) => "number",
        Value::String(_) => "string",
        Value::Table(_) => "table",
        Value::Function(_) => "function",
        Value::Thread(_) => "thread",
        Value::UserData(_) => "userdata",
        Value::Error(_) => "error",
        Value::Other(_) => "other",
    }
}

#[derive(Clone, Debug)]
struct JsonView {
    root: Arc<JsonValue>,
    path: Vec<JsonPathSegment>,
}

#[derive(Clone, Debug)]
enum JsonPathSegment {
    Key(String),
    Index(usize),
}

impl JsonView {
    fn new(root: JsonValue) -> Self {
        Self {
            root: Arc::new(root),
            path: Vec::new(),
        }
    }

    fn nested(&self, segment: JsonPathSegment) -> Self {
        let mut path = self.path.clone();
        path.push(segment);
        Self {
            root: Arc::clone(&self.root),
            path,
        }
    }

    fn current(&self) -> Option<&JsonValue> {
        let mut current = self.root.as_ref();
        for segment in &self.path {
            current = match segment {
                JsonPathSegment::Key(key) => current.get(key)?,
                JsonPathSegment::Index(index) => current.as_array()?.get(*index)?,
            };
        }
        Some(current)
    }

    fn get_key(&self, key: &str) -> Option<Self> {
        self.current()?.get(key)?;
        Some(self.nested(JsonPathSegment::Key(key.to_string())))
    }

    fn get_index(&self, index: usize) -> Option<Self> {
        self.current()?.as_array()?.get(index)?;
        Some(self.nested(JsonPathSegment::Index(index)))
    }
}

impl UserData for JsonView {
    fn add_methods<M: UserDataMethods<Self>>(methods: &mut M) {
        methods.add_meta_method(MetaMethod::Index, |lua, this, key: Value| match key {
            Value::String(key) => {
                let Some(key) = key.to_str().ok() else {
                    return Ok(Value::Nil);
                };
                match this.get_key(&key) {
                    Some(view) => json_view_to_lua(lua, view),
                    None => Ok(Value::Nil),
                }
            }
            Value::Integer(index) if index > 0 => match this.get_index((index - 1) as usize) {
                Some(view) => json_view_to_lua(lua, view),
                None => Ok(Value::Nil),
            },
            Value::Number(index) if index.fract() == 0.0 && index > 0.0 => {
                match this.get_index((index as usize).saturating_sub(1)) {
                    Some(view) => json_view_to_lua(lua, view),
                    None => Ok(Value::Nil),
                }
            }
            _ => Ok(Value::Nil),
        });

        methods.add_meta_method(MetaMethod::Len, |_, this, ()| {
            Ok(this
                .current()
                .and_then(JsonValue::as_array)
                .map_or(0, |v| v.len()))
        });
    }
}

fn json_view_to_lua(lua: &Lua, view: JsonView) -> Result<Value, mlua::Error> {
    match view.current() {
        Some(JsonValue::Null) | None => Ok(Value::Nil),
        Some(JsonValue::Bool(value)) => Ok(Value::Boolean(*value)),
        Some(JsonValue::Number(value)) => {
            if let Some(integer) = value.as_i64() {
                Ok(Value::Integer(integer))
            } else {
                Ok(Value::Number(value.as_f64().unwrap_or_default()))
            }
        }
        Some(JsonValue::String(value)) => lua.create_string(value).map(Value::String),
        Some(JsonValue::Array(_)) | Some(JsonValue::Object(_)) => {
            lua.create_userdata(view).map(Value::UserData)
        }
    }
}
